### ISSUE TITLE
Review Submission

### ISSUE THREAD

**Issue by not-xygen** [KipasTerbang/Teras-Alim#1]
Halo, alim

Kodemu masih kurang terstruktur

1. Pada bagian main, struktur kode seharusnya:

```html
<main>
 <div id=content>
  <section>Konten Deskripsi Website</section>
  <section>Konten-Konten Artikel</section>
  <section>Form Kontak Saya</section>
 </div>
 <aside>"Isi Konten Aside"</div>
</main>
```

2. Pada aside sertakan biodata diri

3. Pada aside, link navigasimu:
![image](https://github.com/KipasTerbang/Teras-Alim/assets/73971391/77fd38a1-5726-4d51-9df0-fc933517762e)
Seharusnya tidak usah pakai titik koma pada akhiran setelah onClick:
`<a href="#" onclick="klikaside()">`

4. Pada baris 148, kami mendapatkan error:
![image](https://github.com/KipasTerbang/Teras-Alim/assets/73971391/f0271cab-cd1b-4c8f-876f-d2bdaa755fa7)
Tutup elemen `<p>` dan `<div>`, sehingga kode menjadi:
```html
<div id="author">
 <p>
  <em>
  Muhammad Nuralimsyah<br />
  22 Mei 2023
  </em>
 </p>
</div>
```

Terimakasih atas submissionnya. Jika sudah selesai direvisi, upload ulang dan silahkan close issue ini

**Comment by nuralims** [comment]
Done bang

**Comment by not-xygen** [comment]
Oke lim, selamat kamu lulus no. 1
